language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - 1.7.1
  - 1.7.2
  - 1.7.3
  - tip

script:
  - go test -coverprofile=xpath2_coverage.txt -covermode=atomic ./xpath2
  - go test -coverprofile=xslt_coverage.txt -covermode=atomic ./xslt

after_success:
  - bash <(curl -s https://codecov.io/bash)
